name: Deploy to GitHub Pages
on:
      push:
        branches:
          - master
jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Build
          run: |
            npm install
            npm run-script build
          env:
            REACT_APP_PLANT_ID_KEY: ${{ secrets.REACT_APP_PLANT_ID_KEY }}

        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            GITHUB_TOKEN: ${{ secrets.REACT_APP_GH_TOKEN }}
            BRANCH: gh-pages
            FOLDER: build
